import { Menu } from "Menu.slint";
import {
    ModuleButton,
    ModuleBinary,
    ModuleColorCode,
    ModuleHexadecimal,
    ModuleKeypad,
    ModuleMathematics,
    ModuleMorse,
    ModuleMultiButtons,
    ModuleTiles,
    ModuleTiming,
    ModuleWires,
} from "Modules/Casual/index.slint";

export enum Pages {
	Menu,
	Binary,
	Button,
	ColorCode,
	CountingNeedy,
	EchoNeedy,
	Hexadecimal,
	InterviewNeedy,
	Keypad,
	Mathematics,
	MorseCode,
	MultiButtons,
	Tiles,
	Timing,
	Wires,
}

export component App inherits Window {
	title: "Defuseler";

    out property <Pages> page: Pages.Menu;

	callback change_to_module_page(int) -> Pages;

	function go_to_menu() {
		page = Pages.Menu;
	}

	Menu {
		visible: page == Pages.Menu;
		button_pressed(id) => {
			page = change_to_module_page(id);
		}
	}
	ModuleButton { visible: page == Pages.Button; back_pressed => {go_to_menu()} }
	ModuleBinary { visible: page == Pages.Binary; back_pressed => {go_to_menu()} }
	ModuleColorCode { visible: page == Pages.ColorCode; back_pressed => {go_to_menu()} }
	ModuleHexadecimal { visible: page == Pages.Hexadecimal; back_pressed => {go_to_menu()} }
	ModuleKeypad { visible: page == Pages.Keypad; back_pressed => {go_to_menu()} }
	ModuleMathematics { visible: page == Pages.Mathematics; back_pressed => {go_to_menu()} }
	ModuleMorse { visible: page == Pages.MorseCode; back_pressed => {go_to_menu()} }
	ModuleMultiButtons { visible: page == Pages.MultiButtons; back_pressed => {go_to_menu()} }
	ModuleTiles { visible: page == Pages.Tiles; back_pressed => {go_to_menu()} }
	ModuleTiming { visible: page == Pages.Timing; back_pressed => {go_to_menu()} }
	ModuleWires { visible: page == Pages.Wires; back_pressed => {go_to_menu()} }
}
