import { Menu } from "Menu.slint";
import {
    ModuleButton,
    ModuleBinary,
    ModuleColorCode,
    ModuleHexadecimal,
    ModuleKeypad,
    ModuleMathematics,
    ModuleMorse,
    ModuleMultiButtons,
    ModuleTiles,
    ModuleTiming,
    ModuleWires,
} from "Modules/Casual/index.slint";

export enum Pages {
	Menu,
	Binary,
	Button,
	ColorCode,
	CountingNeedy,
	EchoNeedy,
	Hexadecimal,
	InterviewNeedy,
	Keypad,
	Mathematics,
	MorseCode,
	MultiButtons,
	Tiles,
	Timing,
	Wires,
}

export component App inherits Window {
	title: "Defuseler";

    out property <Pages> page: Pages.Menu;

	callback change_to_module_page(int) -> Pages;
	callback set_module_answer(Pages, [string]);

	set_module_answer(page, values) => {
		if page == Pages.Button {
			button.set_answer(values);
		} else if page == Pages.Binary {
			binary.set_answer(values);
		} else if page == Pages.ColorCode {
			colorcode.set_answer(values);
		} else if page == Pages.Hexadecimal {
			hex.set_answer(values);
		} else if page == Pages.Keypad {
			keypad.set_answer(values);
		} else if page == Pages.Mathematics {
			math.set_answer(values);
		} else if page == Pages.MorseCode {
			morse.set_answer(values);
		} else if page == Pages.MultiButtons {
			multibuttons.set_answer(values);
		} else if page == Pages.Tiles {
			tiles.set_answer(values);
		} else if page == Pages.Timing {
			timing.set_answer(values);
		} else if page == Pages.Wires {
			wires.set_answer(values);
		}
	}

	function go_to_menu() {
		page = Pages.Menu;
	}

	Menu {
		visible: page == Pages.Menu;
		button_pressed(id) => {
			page = change_to_module_page(id);
		}
	}
	button := ModuleButton { visible: page == Pages.Button; back_pressed => {go_to_menu()} }
	binary := ModuleBinary { visible: page == Pages.Binary; back_pressed => {go_to_menu()} }
	colorcode := ModuleColorCode { visible: page == Pages.ColorCode; back_pressed => {go_to_menu()} }
	hex := ModuleHexadecimal { visible: page == Pages.Hexadecimal; back_pressed => {go_to_menu()} }
	keypad := ModuleKeypad { visible: page == Pages.Keypad; back_pressed => {go_to_menu()} }
	math := ModuleMathematics { visible: page == Pages.Mathematics; back_pressed => {go_to_menu()} }
	morse := ModuleMorse { visible: page == Pages.MorseCode; back_pressed => {go_to_menu()} }
	multibuttons := ModuleMultiButtons { visible: page == Pages.MultiButtons; back_pressed => {go_to_menu()} }
	tiles := ModuleTiles { visible: page == Pages.Tiles; back_pressed => {go_to_menu()} }
	timing := ModuleTiming { visible: page == Pages.Timing; back_pressed => {go_to_menu()} }
	wires := ModuleWires { visible: page == Pages.Wires; back_pressed => {go_to_menu()} }
}
